# Generated by Django 5.2.11 on 2026-02-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileobject',
            options={'ordering': ['-is_folder', 'name']},
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
