"""
Django settings for archive project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ★ .env 파일 로드 (이 코드가 있어야 로컬에서 .env를 읽습니다)
load_dotenv(BASE_DIR / '.env')

# ... (기존 코드) ...

# 3. ALLOWED_HOSTS 설정 (공백 제거 기능 추가)
# 쉼표로 나눈 뒤, 혹시 모를 공백을 제거(.strip())해서 리스트로 만듭니다.
ALLOWED_HOSTS = [
    h.strip() 
    for h in os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-byv6l#1icnibil^(4er@83&jfg3%g#=crmy71+#y$z4!1jgca4'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG가 True이면 개발 모드, False이면 운영 모드
# .env 파일에서 DEBUG=True 또는 DEBUG=False로 조절합니다.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://f.fji.kr').split(',')

# 2. 프록시(Nginx/Cloudflare)를 거쳐서 올 때 HTTPS 인식을 위한 설정
# (내부 통신은 HTTP라도 외부가 HTTPS면 이걸 켜줘야 합니다)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'django.contrib.humanize',
]

# 10GB 업로드 설정 (바이트 단위)
# 10GB = 10 * 1024 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 10737418240
FILE_UPLOAD_MAX_MEMORY_SIZE = 10737418240

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'archive.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'archive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ★ 데이터베이스 설정 분기
if DEBUG:
    # 1. 개발 모드 (DEBUG=True) -> SQLite3 사용
    # 간편하게 파일 DB 사용
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # 2. 운영 모드 (DEBUG=False) -> MariaDB (MySQL) 사용
    # .env 파일에 있는 환경변수를 불러옵니다.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME'),      # .env의 DB_NAME
            'USER': os.environ.get('DB_USER'),      # .env의 DB_USER
            'PASSWORD': os.environ.get('DB_PASSWORD'), # .env의 DB_PASSWORD
            'HOST': os.environ.get('DB_HOST', 'db'),   # docker-compose 서비스명 ('db')
            'PORT': os.environ.get('DB_PORT', '3306'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,  # 최소 4자리부터 허용
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 미디어 파일 설정
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 1. 브라우저를 닫으면 자동으로 로그아웃 (세션 쿠키로 변경)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 2. (선택사항) 브라우저를 켜놔도 30분 동안 활동 없으면 자동 로그아웃
# 보안을 강화하려면 이 설정도 추천합니다. (초 단위: 30분 = 1800초)
SESSION_COOKIE_AGE = 1800

# 3. 활동(클릭 등)이 있을 때마다 세션 유효시간 갱신
SESSION_SAVE_EVERY_REQUEST = True

# 경비원에게: "로그인 필요한 사람은 /accounts/login/ 말고, 그냥 /login/ 으로 보내세요."
LOGIN_URL = '/login/'

# 로그인 성공하면 메인 페이지('/')로 보내세요.
LOGIN_REDIRECT_URL = '/'

# 로그아웃 하면 다시 로그인 페이지로 보내세요.
LOGOUT_REDIRECT_URL = '/login/'